version: '2'
services:
  eureka:
   #build: ../refarch-cloudnative-netflix-eureka/docker
   image: netflix-eureka
   ports:
    - "8761:8761"

  config:
   #build: ../refarch-cloudnative-spring-config/docker
   image: spring-config
   links:
    - eureka
    - zipkin
   ports:
    - "8888"
   env_file:
    - wfd.env

  zuul:
   #build: ../refarch-cloudnative-netflix-zuul/docker
   image: netflix-zuul
   links:
    - eureka
    - zipkin
   ports:
    - "80:8080"
   env_file:
    - wfd.env

  turbine:
   #build: ../refarch-cloudnative-netflix-turbine/docker
   image: netflix-turbine
   links:
    - eureka
    - config
    - zipkin
   ports:
    - "8989:8989"
    - "8990:8990"
   env_file:
    - wfd.env

  zipkin:
   #build: ../refarch-cloudnative-zipkin/docker
   image: zipkin
   links:
    - eureka
   ports:
    - "9411:9411"
   env_file:
    - wfd.env

  ui:
   #build: ../refarch-cloudnative-wfd-ui/docker
   image: wfd-ui
   links:
    - eureka
    - config
    - zipkin
   ports:
    - "8181"
    - "9181"
   env_file:
    - wfd.env

  menu:
   #build: ../refarch-cloudnative-wfd-menu/docker
   image: wfd-menu
   links:
    - eureka
    - config
    - zipkin
   ports:
    - "8180"
    - "9180"
   env_file:
    - wfd.env

  appetizer:
   #build: ../refarch-cloudnative-wfd-appetizer/docker
   image: wfd-appetizer
   ports:
    - "8082"
   links:
    - eureka
    - config
    - zipkin
   env_file:
    - wfd.env

  entree:
   #build: ../refarch-cloudnative-wfd-entree/docker
   image: wfd-entree
   links:
    - eureka
    - config
    - zipkin
   ports:
    - "8081"
   env_file:
    - wfd.env

  dessert:
   #build: ../refarch-cloudnative-wfd-dessert/docker
   image: wfd-dessert
   links:
    - eureka
    - config
    - zipkin
   ports:
    - "8083"
   env_file:
    - wfd.env
